services:
  web:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


